=== AngelCalvoOro/LMSG/CONTENIDO XML/EJERCICIOS/Ejercicio DTD y XML Schema 2/ejercicios DTD/EJ-2/agenda.dtd
<!ELEMENT agenda (contactos)*>
<!ELEMENT contactos (nombre,direccion,ciudad,codigo_postal,numeros,email,web,compañia)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT numeros(telefono,fax)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT compañia (#PCDATA)>

=== AngelCalvoOro/LMSG/CONTENIDO XML/EJERCICIOS/Ejercicio DTD y XML Schema 2/ejercicios DTD/EJ-2/agenda.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
	<contactos>
		<nombre>pepe</nombre>
		<direccion>calle prueba</direccion>
		<ciudad>Vitoria</ciudad>
		<codigo_postal>05050</codigo_postal>
		<numeros>
			<telefono>667875245</telefono>
			<fax>575895743</fax>
		</numeros>
		<email>ejercicio2@ejercicio2.com</email>
		<web>http://ninguno.org</web>
		<compañia>Industrias Ejercicio</compañia>
	</contactos>
</agenda>
